const works_library = {
    'hakomob': {
        'title': 'HakoMob(ハコモブ)',
        'image': './assets/img/hakomob1.png',
        'image2': './assets/img/hakomob2.png',
        'image3': './assets/img/hakomob3.png',
        'explain': [
                    '',
                    'ユーザーがモバイルで描いた絵が、AR空間上に浮かび上がるwebARアプリケーションです。',
                    '大学のプロジェクト学習で作成しました。',
                    '<a href="https://www.fun.ac.jp/project-learning" target="_blank" rel="noopener noreferrer" style="color: #007bff; text-decoration: underline;">(複数人でテーマに沿って、問題提起から問題解決までのプロセスを行う通年授業)</a>',
                    '『AR技術で棒二森屋跡地(函館駅前)をハックする』というテーマから、学生が主体となって開発したものです。',
                    'WebARアプリケーション向けの開発プラットフォームの8thwallを使用しています。',
                    '主に、3Dモデルの作成・ユーザの描画を3Dモデルのテクスチャに適用するシステム・お絵描き画面のUI/UXデザインとフロントエンド作成・DBへの保存関連のシステム等を担当しました',
                    '',
                    '・HTML・CSS・javascript・A-Frame・Firebase・Blender・Illustrator・Figma',
                    ].join('<br>'),
        'github': '',
        'link': ''
    },
    'memocolle': {
        'title': 'MemoColle(メモコレ)',
        'image': './assets/img/memocolle1.png',
        'image2': './assets/img/memocolle2.png',
        'image3': './assets/img/memocolle3.png',
        'explain': [
                    '',
                    'スマホで撮った大切な思い出の写真を思い出させてくれる、モバイルネイティブアプリケーションです。',
                    '未来大在学時に学内ハッカソン「P2hacks2024」で作成しました。',
                    '',
                    '',
                    '・bootstrap・javascript(jQuery)・python(Django)・Postgres・gunicorn・nginx・github',
                    'deploy → sakuraVPS',
                    ].join('<br>'),
        'github': 'https://github.com/darca116',
        'link': ''
    },
    'my_portfolio': {
        'title': 'Portforlio',
        'image': './assets/img/portfolio1.png',
        'image2': './assets/img/portfolio2.png',
        'image3': './assets/img/portfolio3.png',
        'explain': [
                    '',
                    'このサイトです。主にbootstrapを使用して作成しています。',
                    '大枠はインターネット上のテンプレートをもとにし、細部はbootstrapのコンポーネントやライブラリを用いてカスタマイズしています。',
                    '携帯で見てもPCでも見ても表示が崩れないレスポンシブデザインを意識して作成しました。',
                    '動く背景はhtml canvasにjavascriptでアニメーションを描画しています。',
                    'アニメーションの基礎となるソースコードをchatgptに作成してもらい、カスタマイズしました。',
                    '',
                    '・bootstrap・javascript(jQuery)・nginx・github',
                    'deploy → sakuraVPS',
                    ].join('<br>'),
        'github': 'https://github.com/darca116/darca116.github.io',
        'link': ''
    },
    'maze': {
        'title': 'maze',
        'image': './assets/img/maze.png',
        'image2': './assets/img/maze2.png',
        'image3': './assets/img/maze3.png',
        'explain': [
                    '',
                    'n*n の迷路をランダムに自動生成するjavascriptです。動かす場合はgithubからダウンロードしてください。',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・javascript(jQuery)・',
                    '',
                    ].join('<br>'),
        'github': 'https://github.com/darca116',
        'link': ''
    },
    'othello': {
        'title': 'othello',
        'image': './assets/img/othello.png',
        'image2': './assets/img/othello2.png',
        'image3': './assets/img/othello3.png',
        'explain': [
                    '',
                    '社会人2年目くらいの時に作ったオセロゲームです。githubからダウンロードして遊んでください。',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・javascript(jQuery)・',
                    '',
                    ].join('<br>'),
        'github': '',
        'link': 'https://github.com/darca116'
    },
    'typing': {
        'title': 'typing',
        'image': './assets/img/typing.png',
        'image2': './assets/img/typing2.png',
        'image3': './assets/img/typing3.png',
        'explain': [
                    '',
                    'かなり昔に作ったシンプルなタイピングゲームです。githubからダウンロードして遊べます。',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・javascript(jQuery)・',
                    '',
                    ].join('<br>'),
        'github': 'https://github.com/darca116',
        'link': 'https://github.com/darca116'
    },
}