const works_library = {
    'hakomob': {
        'title': 'HakoMob(ハコモブ)',
        'image': './assets/img/hakomob1.png',
        'image2': './assets/img/hakomob2.png',
        'image3': './assets/img/hakomob3.png',
        'explain': [
                    '',
                    'ユーザーがモバイルで描いた絵が、AR空間上に浮かび上がるwebARアプリケーションです。',
                    '大学のプロジェクト学習で制作しました。',
                    '<a href="https://www.fun.ac.jp/project-learning" class="modal-link" target="_blank" rel="noopener noreferrer">(学生が複数人でテーマに沿って、問題提起から問題解決までのプロセスを行う通年授業)</a>',
                    '',
                    '『AR技術で棒二森屋跡地(函館駅前)をハックする』というテーマから、学生が主体となって開発したものです。',
                    'AR空間に出現するお絵描きが街で自由に動き回ることで、閉店してしまった棒二森屋跡地に再び「にぎわい」を生み出すことを目指します。',
                    '',
                    'WebARアプリケーション向け開発プラットフォームの8thwallを使用しています。',
                    '主に、3Dモデルの作成・ユーザの描画を3Dモデルのテクスチャに適用するシステム・お絵描き画面のUI/UXデザインとフロントエンド作成・DBへの保存関連のシステム等を担当しました。',
                    '',
                    '・8thWall・HTML・CSS・JavaScript・A-Frame・Firebase・Blender・Adobe Illustrator・Figma',
                    ].join('<br>'),
        'github': '',
        'link': '',
        'slide': ''
    },
    'memocolle': {
        'title': 'MemoColle(メモコレ)',
        'image': './assets/img/memocolle1.jpg',
        'image2': './assets/img/memocolle2.jpg',
        'image3': './assets/img/memocolle3.jpg',
        'explain': [
                    '',
                    'スマホで撮った大切な思い出の写真を振り返る、モバイルアプリケーションです。',
                    '未来大在学時に学内ハッカソン<a href="https://p2hacks2024.github.io/" class="modal-link" target="_blank" rel="noopener noreferrer">P2hacks2024</a>で制作しました。',
                    '',
                    '『フラッシュ』というP2hacks2024の共通テーマから、思い出を想起する「フラッシュバック」や、カメラの「フラッシュ」を連想してコンセプトを練っていきました。',
                    'ユーザーの思い出の写真をピックアップした後、時系列順に並び替えるクイズが出題され、正解すると写真が美術館へ登録されます。',
                    'この一連の流れを通して、普段から写真フォルダを見返す人にも新鮮さを提供しつつ、思い出を振り返る体験ができます。',
                    '',
                    '主にエンジニアサイドとして参加し、フロントエンド・バックエンドの双方を担当しました。',
                    'P2hacksのスポンサーである、ソフトクリエイト様から企業賞を受賞することができました。',
                    '',
                    '・AndroidStudio・XML・Java・AndoroidSDK・GitHub',
                    ].join('<br>'),
        'github': 'https://github.com/p2hacks2024/pre-18',
        'link': '',
        'slide': 'https://drive.google.com/file/d/1ZQbcCV8CokfQq7UqUEY2O71vckDAXcT-/preview'
    },
    'my_portfolio': {
        'title': 'Portforlio',
        'image': './assets/img/portfolio1.png',
        'image2': './assets/img/portfolio2.png',
        'image3': './assets/img/portfolio3.png',
        'explain': [
                    '',
                    'このサイトです。主にbootstrapで作成して、GitHubPagesを通して公開しています。',
                    '就職活動や、今後の作品をまとめるために制作しました。',
                    '',
                    '大枠は<a href="https://startbootstrap.com/theme/resume" class="modal-link" target="_blank" rel="noopener noreferrer">インターネット上のテンプレート</a>をもとにし、細部はbootstrapのコンポーネントやライブラリを用いてカスタマイズしています。',
                    '携帯で見てもPCでも見ても表示が大きく崩れない、レスポンシブデザインを意識して制作しました。',
                    '',
                    '・HTML・CSS・JavaScript(jQuery)・Bootstrap・GitHub',
                    ].join('<br>'),
        'github': 'https://github.com/darca116/darca116.github.io',
        'link': 'https://darca116.github.io/',
        'slide': ''
    },
    'tatol': {
        'title': 'ギタイシュガメ',
        'image': './assets/img/tatol1.png',
        'image2': './assets/img/tatol2.png',
        'image3': './assets/img/tatol3.png',
        'explain': [
                    '',
                    '未来大に生息する仮想生物の作品です。函館を守るカメの神様の幼体をイメージしています。',
                    '『公立はこだて未来大学に生息する仮想生物』をテーマに、Arduinoを活用する授業で制作しました。',
                    '',
                    '未来大に多く設置されている円卓テーブルをモチーフに、大学の住所である亀田ともかけて、カメの守り神という設定を考えました。',
                    'まだ子どもなので擬態は出来ず、好奇心旺盛なので逆に人間に気付いてもらおうとしています。',
                    'そのため人が近づくと自らを光らせて居場所を知らせようとします。',
                    '',
                    'IllustratorやBlenderでイメージを形にして、レーザー加工機・3Dプリンターなどで実際のモノを作りました。',
                    '台座の下にはArudinoやセンサー類が隠されていて、検知していないと首を振って周囲を見渡し、検知すると発光するようになっています。',
                    '大学に編入して初めての実習的な授業だったため戸惑いもありましたが、かなり楽しく制作できた作品です。',
                    '',
                    '・Arduino・Blender・Adobe Illustrator・レーザー加工機・3Dプリンター',
                    ].join('<br>'),
        'github': '',
        'link': '',
        'slide': ''
    },
    'solme': {
        'title': 'Solme(ソルミー)',
        'image': './assets/img/solme1.png',
        'image2': './assets/img/solme2.png',
        'image3': './assets/img/solme3.png',
        'explain': [
                    '',
                    '日光を浴びることを習慣化させてくれる、モバイルアプリケーションです。',
                    '未来大在学時に学外ハッカソン<a href="https://spajam.jp/" class="modal-link" target="_blank" rel="noopener noreferrer">SPAJAM2025</a>で制作しました',
                    '',
                    '『バランス』というテーマから生活バランスに着目して、日光を浴びることで生活バランスを整えることをコンセプトにしました。',
                    '日光を浴びた時間を、AIで生成する自らのアバターの体調や様子を使って可視化することで、ユーザーの行動変容を促します。',
                    '',
                    '主にデザイナーサイドとして参加し、UI/UXデザイン・ロゴデザイン・発表用スライドの作成を担当しました。',
                    '',
                    '・Adobe Illustrator・Figma・GituHub',
                    ].join('<br>'),
        'github': '',
        'link': '',
        'slide': ''
    },
    'typing': {
        'title': 'typing',
        'image': './assets/img/typing.png',
        'image2': './assets/img/typing2.png',
        'image3': './assets/img/typing3.png',
        'explain': [
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・',
                    '',
                    ].join('<br>'),
        'github': 'https://github.com/darca116',
        'link': 'https://github.com/darca116',
        'slide': ''
    },
}