const works_library = {
    'hakomob': {
        'title': 'HAKO MOB(ハコモブ)',
        'image': './assets/img/hakomob1.png',
        'image2': './assets/img/hakomob2.png',
        'image3': './assets/img/hakomob3.png',
        'explain': [
                    '',
                    'ユーザーがモバイルで描いた絵が、AR空間上に浮かび上がるwebアプリケーションです',
                    '大学のプロジェクト学習(複数人でテーマに沿って、問題提起から問題解決までのプロセスを行う通年授業)で作成しました。',
                    '『AR技術で棒二森屋跡地(函館駅前)をハックする』というテーマから、学生が主体となって開発したものです。',
                    '8thwallというWebARアプリケーション向けの開発プラットフォームを使用しています。',
                    '私は主に、3Dモデルの作成・お絵描き画面のデザインとフロントエンドの作成・ユーザが描いた絵のDBへの保存関連のプログラムを担当しました',
                    '',
                    'javascript・A-Frame・Firebase・Blender・Figma',
                    ].join('<br>'),
        'github': '',
        'link': ''
    },
    'team_portal': {
        'title': 'Team Portal',
        'image': './assets/img/teamportal.png',
        'image2': './assets/img/teamportal2.png',
        'image3': './assets/img/teamportal3.png',
        'explain': [
                    '',
                    'しばらくの間、SEの友人たちと開催していた勉強会(?)で友人たちが作った成果物を共有するためのサイトを自作してみました。',
                    '作成中に勉強会が自然消滅してしまい、結局成果物登録をしているのは私だけの状態です。',
                    '画面側はbootstrapを使用して作成しました。bootstrap勉強始めたての頃なのでＵＩはなんだか微妙です。',
                    'バックエンドはDjangoで実装しています。',
                    '画像ファイルやソースコードをアップロードしたり、リンクを登録することが可能です。',
                    '',
                    '・bootstrap・javascript(jQuery)・python(Django)・Postgres・gunicorn・nginx・github',
                    'deploy → sakuraVPS',
                    ].join('<br>'),
        'github': 'https://github.com/darca116',
        'link': ''
    },
    'my_portfolio': {
        'title': 'Portforlio',
        'image': './assets/img/portfolio1.png',
        'image2': './assets/img/portfolio2.png',
        'image3': './assets/img/portfolio3.png',
        'explain': [
                    '',
                    'このサイトです。主にbootstrapを使用して作成しています。',
                    '大枠はインターネット上のテンプレートをもとにし、細部はbootstrapのコンポーネントやライブラリを用いてカスタマイズしています。',
                    '携帯で見てもPCでも見ても表示が崩れないレスポンシブデザインを意識して作成しました。',
                    '動く背景はhtml canvasにjavascriptでアニメーションを描画しています。',
                    'アニメーションの基礎となるソースコードをchatgptに作成してもらい、カスタマイズしました。',
                    '',
                    '・bootstrap・javascript(jQuery)・nginx・github',
                    'deploy → sakuraVPS',
                    ].join('<br>'),
        'github': 'https://github.com/darca116/darca116.github.io',
        'link': ''
    },
    'maze': {
        'title': 'maze',
        'image': './assets/img/maze.png',
        'image2': './assets/img/maze2.png',
        'image3': './assets/img/maze3.png',
        'explain': [
                    '',
                    'n*n の迷路をランダムに自動生成するjavascriptです。動かす場合はgithubからダウンロードしてください。',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・javascript(jQuery)・',
                    '',
                    ].join('<br>'),
        'github': 'https://github.com/darca116',
        'link': ''
    },
    'othello': {
        'title': 'othello',
        'image': './assets/img/othello.png',
        'image2': './assets/img/othello2.png',
        'image3': './assets/img/othello3.png',
        'explain': [
                    '',
                    '社会人2年目くらいの時に作ったオセロゲームです。githubからダウンロードして遊んでください。',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・javascript(jQuery)・',
                    '',
                    ].join('<br>'),
        'github': 'https://github.com/darca116',
        'link': ''
    },
    'typing': {
        'title': 'typing',
        'image': './assets/img/typing.png',
        'image2': './assets/img/typing2.png',
        'image3': './assets/img/typing3.png',
        'explain': [
                    '',
                    'かなり昔に作ったシンプルなタイピングゲームです。githubからダウンロードして遊べます。',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・javascript(jQuery)・',
                    '',
                    ].join('<br>'),
        'github': 'https://github.com/darca116',
        'link': ''
    },
}